---
driver:
  name: ssh_cisco
  hostname: 192.168.122.250
  username: kitchen
  password: insecure
  ssh_command_prefix: 'sudo ip netns exec management su -l kitchen -c'

provisioner:
  name: chef_zero

platforms:
  - name: n9kv-windriver

suites:
  - name: default
    run_list:
      - recipe[cisco-test::default]
    attributes:
