---
driver:
  name: vagrant
  provider: virtualbox
  vm_hostname: false
  provision: true

provisioner:
  name: chef_zero

platforms:
  - name: nexus
    driver:
      box: n9kv
      vagrantfiles:
        - vagrantfiles/nexus.rb
    provisioner:
      command_prefix: sudo ip netns exec management sudo -u vagrant
    verifier:
      command_prefix: sudo ip netns exec management sudo -u vagrant
  - name: ios_xr
    driver:
      box: ucs-fullk9
      vagrantfiles:
        - vagrantfiles/ios_xr.rb

suites:
  - name: full
    includes:
      - nexus
    run_list:
      - recipe[cisco-test::full]
    attributes:
  - name: basic
    includes:
      - ios_xr
    run_list:
      - recipe[cisco-test::basic]
    attributes:
