AllCops:
  Include:
    - attributes/*.rb
    - docs/*.rb
    - libraries/*.rb
    - recipes/*.rb
    - spec/**/*.rb
  Exclude:
    - metadata.rb
    - files/**/*
    - vendor/**/*

# Baseline code complexity metrics - we should try and reduce these over time
Metrics/AbcSize:
  Max: 157

Metrics/ClassLength:
  Max: 132

Metrics/CyclomaticComplexity:
  Max: 31

Metrics/LineLength:
  Max: 118

Metrics/MethodLength:
  Max: 110

Metrics/PerceivedComplexity:
  Max: 32

#
# Team preferences different from Rubocop defaults:
#

# We like table alignment for readability
Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Template files have wildcard strings in class names
Style/ClassAndModuleCamelCase:
  Exclude:
    - docs/*.rb

# Use is_a? and kind_of? interchangeably
Style/ClassCheck:
  Enabled: false

# Template files have atypical file names on purpose
Style/FileName:
  Exclude:
    - docs/*.rb

# As a team we like 'sprintf' rather than 'format'
Style/FormatString:
  EnforcedStyle: sprintf

# Mixed keys are ugly. Use one or the other as needed
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Template files have wildcard strings in method names
Style/MethodName:
  Exclude:
    - docs/*.rb

# Recipes shouldn't use underscores in numeric literals
Style/NumericLiterals:
  Exclude:
    - recipes/*.rb

# "def foo(bar=baz)" not "def foo(bar = baz)"
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

# Let us use table-style formatting in our recipes
Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - recipes/*.rb

# Make it neater to extend multi-line arrays and hashes
Style/TrailingComma:
  EnforcedStyleForMultiline: comma

# Template files have wildcard strings in variable names
Style/VariableName:
  Exclude:
    - docs/*.rb
