#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          demo-one
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      0 1 6
# Short-Description: demo-one
# Description:       demo-one
### END INIT INFO

test -f /usr/bin/demo-one || exit 0

case "$1" in
    start)
        echo "Starting demo-one daemon..."
        start-stop-daemon --start --quiet --exec /usr/bin/demo-one &
        ;;
    stop)
        echo "Stopping demo-one daemon..."
        start-stop-daemon --stop --quiet --exec /usr/bin/demo-one
        ;;
    reload)
        ;;
    force-reload)
        $0 restart
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: /etc/init.d/demo-one {start|stop|reload|restart}"
        exit 1
        ;;
esac

exit 0

